// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type User struct {
	ID          int64  `json:"id"`
	PhoneNumber string `json:"phone_number"`
	Email       string `json:"email"`
	Username    string `json:"username"`
	// hashed password
	Password string `json:"password"`
	// role-based access: admin, seller, or buyer
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}
